name: HHS Breach Scraper

on:
  schedule:
    - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  breach:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 pandas

      - name: Clone GitHub Pages repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/onalos/onalos.github.io.git repo

      - name: Run scraper
        run: |
          python scraper.py
          cp index.html raw.html breaches.csv breaches.json repo/

      - name: Commit and push
        run: |
          cd repo
          git config user.name "Breach Bot"
          git config user.email "actions@github.com"
          git add index.html raw.html breaches.csv breaches.json
          git diff --cached --quiet || git commit -m "Update breach section"
          git push origin HEAD:main
