name: HHS Breach Scraper

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 pandas

      - name: Manually clone repo using PAT
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/onalos/onalos.github.io.git repo

      - name: Run scraper in cloned repo
        run: |
          cd repo
          python scraper.py

      - name: Commit and push from authenticated repo
        run: |
          cd repo
          git config user.name "Breach Bot"
          git config user.email "actions@github.com"
          git add index.html
          git diff --cached --quiet || git commit -m "Update breach report"
          git push origin HEAD:main
