name: HHS Breach Scraper

on:
  schedule:
    - cron: '0 0,12 * * *'  # Every 12 hours (UTC)
  workflow_dispatch:        # Manual trigger

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Google Chrome via apt repo
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo gpg --dearmor -o /usr/share/keyrings/google-chrome.gpg
          echo "deb [arch=amd64 signed-by=/usr/share/keyrings/google-chrome.gpg] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install matching ChromeDriver
        run: |
          CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+')
          CHROME_MAJOR=$(echo "$CHROME_VERSION" | cut -d '.' -f 1)
          DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_MAJOR")
          wget "https://chromedriver.storage.googleapis.com/${DRIVER_VERSION}/chromedriver_linux64.zip"
          unzip chromedriver_linux64.zip
          sudo mv chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver

      - name: Install Python dependencies
        run: pip install selenium beautifulsoup4 pandas

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push if changed
        run: |
          git config --global user.name 'Breach Bot'
          git config --global user.email 'breachbot@example.com'
          git add index.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Auto-update breach report"
          git push

