name: HHS Breach Scraper

on:
  schedule:
    - cron: '0 0,12 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 pandas

      - name: Clone repo using PAT
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/onalos/onalos.github.io.git repo

      - name: Run scraper
        run: |
          python scraper.py
          cp index.html raw.html repo/

      - name: Commit and push output
        run: |
          cd repo
          git config user.name "Breach Bot"
          git config user.email "actions@github.com"
          git add index.html raw.html
          git status
          git diff --cached --quiet || git commit -m "Update breach report and raw page"
          git push origin HEAD:main
