name: HHS Breach Scraper

on:
  schedule:
    - cron: '0 0,12 * * *'  # Every 12 hours UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 pandas

      - name: Run scraper
        run: python scraper.py

      - name: Commit and push if index.html changed
        run: |
          git config --global user.name "Breach Bot"
          git config --global user.email "actions@github.com"
          git add index.html
          git diff --quiet && git diff --staged --quiet || git commit -m "Update breach report"
          git push https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/onalos/onalos.github.io.git HEAD:main
