name: HHS Breach Page Generator

on:
  schedule:
    - cron: '0 15 * * *'  # 10:00 AM ET
  workflow_dispatch:

jobs:
  breach:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests beautifulsoup4 pandas

      - name: Clone GitHub Pages repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/onalos/onalos.github.io.git repo

      - name: Copy base HTML template
        run: |
          cp repo/base_template.html .

      - name: Run HHS scraper
        run: |
          python hhs_scraper.py
          cp breaches.html raw.html breaches.csv breaches.json repo/

      - name: Commit and push
        run: |
          cd repo
          git config user.name "Breach Bot"
          git config user.email "actions@github.com"
          git add breaches.html raw.html breaches.csv breaches.json
          git diff --cached --quiet || git commit -m "Update HHS breach page"
          git push origin HEAD:main
