name: Threat News Page Generator

on:
  schedule:
    - cron: '5 15 * * *'  # Daily at 10:05am ET
  workflow_dispatch:

jobs:
  generate-news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install feedparser

      - name: Clone GitHub Pages repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/onalos/onalos.github.io.git site

      - name: Generate news.html
        run: |
          cp site/base_template.html .
          python news_scraper.py
          cp news.html site/

      - name: Commit and push
        run: |
          cd site
          git config user.name "News Bot"
          git config user.email "actions@github.com"
          git add news.html
          git diff --cached --quiet || git commit -m "Update news section"
          git push origin HEAD:main
