name: Healthcare Threat News Fetcher

on:
  schedule:
    - cron: '5 15 * * *'  # Daily at 15:05 UTC (just after breach scraper)
  workflow_dispatch:

jobs:
  news:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install feedparser

      - name: Clone GitHub Pages repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/onalos/onalos.github.io.git repo

      - name: Run news scraper and append to site
        run: |
          python news_scraper.py
          cp news.html repo/
          cd repo
          cp ../index.html .  # Pull in current breach file to update
          python ../scraper.py  # Rebuild index.html with appended news section

      - name: Commit and push
        run: |
          cd repo
          git config user.name "News Bot"
          git config user.email "actions@github.com"
          git add index.html news.html
          git diff --cached --quiet || git commit -m "Update with latest healthcare news"
          git push origin HEAD:main
