name: Healthcare Threat News Fetcher

on:
  schedule:
    - cron: '5 15 * * *'  # 10:05am Eastern
  workflow_dispatch:

jobs:
  news:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install feedparser

      - name: Clone GitHub Pages repo
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/onalos/onalos.github.io.git repo

      - name: Run news scraper
        run: |
          cd repo
          python ../news_scraper.py
          cp index.html .

      - name: Commit and push
        run: |
          git config user.name "News Bot"
          git config user.email "actions@github.com"
          git add index.html
          git diff --cached --quiet || git commit -m "Update news section"
          git push origin HEAD:main
